config/routes.rb
Rails.application.routes.draw do

  resources :positions do
    resources :reviews
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, presence: true,
                    length: {minimum: 3 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:title, :created_at, :location, :kind, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @position = Position.find(params[:position_id])
    @review = @position.reviews.create(review_params)
    redirect_to position_path(@position)
  end

  def destroy
    @position = Position.find(params[:position_id])
    @review = @position.reviews.find(params[:id])
    @review.destroy
    redirect_to position_path(@position)
  end

  private
    def review_params
      params.require(:review).permit(:comment, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :position_title %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.text_field :created_at, id: :position_created_at %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :position_location %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.text_field :kind, id: :position_kind %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :position_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th>Location</th>
      <th>Kind</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.title %></td>
        <td><%= position.created_at %></td>
        <td><%= position.location %></td>
        <td><%= position.kind %></td>
        <td><%= position.description %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @position.title %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @position.created_at %>
</p>

<p>
  <strong>Location:</strong>
  <%= @position.location %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @position.kind %>
</p>

<p>
  <strong>Description:</strong>
  <%= @position.description %>
</p>

<h2>Reviews</h2>
<%= render @position.reviews %>


<h2>Add a review:</h2>
<%= render 'reviews/form' %>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: [ @position, @position.reviews.build ], local: true) do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
  </p>
  <p>
    <%= form.label :rating %><br>
    <%= form.number_field :rating %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
  <%= link_to 'Destroy Review', [review.position, review],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>